// Code generated by goctl. DO NOT EDIT.
package types

type ChatRequest struct {
	FormId   int64  `json:"form_id"`   // 信息发送者
	TargetId int64  `json:"target_id"` // 信息接收者
	Type     int64  `json:"type"`      // 聊天类型:私聊 1 群聊2  广播3
	Media    int64  `json:"media"`     // 信息类型:文字1 图片2 音频3
	Content  string `json:"content"`   // 消息内容
	Pic      string `json:"pic"`       // 图片相关
	Url      string `json:"url"`       // 文件相关
	Desc     string `json:"desc"`      // 文件描述
	Amount   int64  `json:"amount"`    // 其他数据大小
}

type ChatResponse struct {
	Msg string `json:"msg"`
}

type GetMsgRequest struct {
	FormId   int64 `json:"form_id"`   // 信息发送者
	TargetId int64 `json:"target_id"` // 信息接收者
	Start    int64 `json:"start"`     // 开始下标
	Stop     int64 `json:"stop"`      // 结束下标
	Reverse  bool  `json:"reverse"`   // 是否倒序
}

type GetMsgResponse struct {
	Msgs []string `json:"msgs"`
}
