// Code generated by goctl. DO NOT EDIT.
package types

type AddFriendRequest struct {
	Uid  int64 `json:"uid"`
	Tid  int64 `json:"tid"`
	Type int64 `json:"type"`
}

type AddGroupRequest struct {
	Uid  int64  `json:"uid"`
	Name string `json:"name"`
}

type DelFriendRequest struct {
	Uid  int64 `json:"uid"`
	Tid  int64 `json:"tid"`
	Type int64 `json:"type"`
}

type DelGroupRequest struct {
	Uid  int64  `json:"uid"`
	Name string `json:"name"`
}

type GetFriendsRequest struct {
	Uid  int64 `json:"uid"`
	Type int64 `json:"type"`
}

type GetFriendsResponse struct {
	Tid []int64 `json:"tid"`
}

type GetGroupsRequest struct {
	Uid int64 `json:"uid"`
}

type GetGroupsResponse struct {
	Groups []Group `json:"groups"`
}

type Group struct {
	Gid  int64  `json:"gid"`
	Name string `json:"name"`
}
